version: 2.1

# More about orbs: https://circleci.com/docs/2.0/using-orbs/
# orbs:
#   ruby: circleci/ruby@1.1.2

commands:
  pip-install-deps-27:
    parameters:
      requirements:
        default: "tests/requirements-27.txt"
        type: string
    steps:
      - run:
          name: Install Python 2.7 Dependencies
          command: |
            rm -rf venv
            export PATH=/home/circleci/.local/bin:$PATH
            pip install --user -U pip setuptools virtualenv wheel
            virtualenv --python=python2.7 --always-copy venv
            . venv/bin/activate
            pip install 'wheel>=0.29.0'
            pip install -r requirements.txt
            pip install -r <<parameters.requirements>>

  pip-install-deps:
    parameters:
      requirements:
        default: "tests/requirements.txt"
        type: string
    steps:
      - run:
          name: Install Python Dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install 'wheel>=0.29.0'
            pip install -r requirements.txt
            pip install -r <<parameters.requirements>>

  install-couchbase-deps:
    steps:
      - run:
          name: Install Couchbase Dependencies
          command: |
            sudo apt-get update
            sudo apt install lsb-release -y
            curl -O https://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0-6-amd64.deb
            sudo dpkg -i ./couchbase-release-1.0-6-amd64.deb
            sudo apt-get update
            sudo apt install libcouchbase-dev -y

  python37:
    docker:
      - image: circleci/python:3.7.9
      - image: circleci/postgres:9.6.5-alpine-ram
      - image: circleci/mariadb:10-ram
      - image: circleci/redis:5.0.4
      - image: rabbitmq:3.5.4
      - image: circleci/mongo:4.2.3-ram
      - image: singularities/pubsub-emulator
        environment:
          PUBSUB_PROJECT_ID: "project-test"
          PUBSUB_LISTEN_ADDRESS: "0.0.0.0:8432"
    working_directory: ~/repo
    steps:
      - checkout
      - pip-install-deps
      - run:
          name: run tests
          environment:
            INSTANA_TEST: "true"
          command: |
            . venv/bin/activate
            # We uninstall uvloop as it interferes with asyncio changing the event loop policy
            pip uninstall -y uvloop
            pytest -v

  python38:
    docker:
      - image: circleci/python:3.8.6
      - image: circleci/postgres:9.6.5-alpine-ram
      - image: circleci/mariadb:10-ram
      - image: circleci/redis:5.0.4
      - image: rabbitmq:3.5.4
      - image: circleci/mongo:4.2.3-ram
      - image: singularities/pubsub-emulator
        environment:
          PUBSUB_PROJECT_ID: "project-test"
          PUBSUB_LISTEN_ADDRESS: "0.0.0.0:8432"
    working_directory: ~/repo
    steps:
      - checkout
      - pip-install-deps
      - run:
          name: run tests
          environment:
            INSTANA_TEST: "true"
          command: |
            . venv/bin/activate
            coverage run --source=instana -m pytest -v
            coverage report -m
            coverage html
      - store_artifacts:
          path: htmlcov

workflows:
  version: 2
  build:
    jobs:
      - python37
      - python38
